// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "Eko Kurniawan",
            "email": "ekokurniawaann@gmail.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/register": {
            "post": {
                "description": "Registrasi akun pengguna baru ke sistem FortisFit.",
                "tags": [
                    "Auth"
                ],
                "summary": "Register Akun Baru",
                "parameters": [
                    {
                        "description": "body",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.RegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/responseswagger.RegisterSuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/responseswagger.BadRequestResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/responseswagger.ConflictResponse"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/responseswagger.ValidationFailedResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/responseswagger.InternalServerErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/verify": {
            "get": {
                "description": "Memvalidasi token dari email untuk mengubah status is_verified menjadi true.",
                "tags": [
                    "Auth"
                ],
                "summary": "Verify User Email",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Email Pengguna",
                        "name": "email",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Token Verifikasi Kriptografis",
                        "name": "token",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/responseswagger.VerifyEmailSuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Token atau email tidak valid",
                        "schema": {
                            "$ref": "#/definitions/responseswagger.BadRequestResponse"
                        }
                    },
                    "422": {
                        "description": "Gagal lolos validasi format",
                        "schema": {
                            "$ref": "#/definitions/responseswagger.ValidationFailedResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/responseswagger.InternalServerErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.RegisterRequest": {
            "type": "object",
            "required": [
                "email",
                "full_name",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "full_name": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "responseswagger.BadRequestResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "format json tidak valid"
                }
            }
        },
        "responseswagger.ConflictResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "data sudah terdaftar"
                }
            }
        },
        "responseswagger.InternalServerErrorResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "internal server error"
                }
            }
        },
        "responseswagger.RegisterSuccessResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "pendaftaran berhasil"
                }
            }
        },
        "responseswagger.ValidationFailedResponse": {
            "type": "object",
            "properties": {
                "errors": {
                    "type": "object",
                    "properties": {
                        "email": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            },
                            "example": [
                                "format email salah"
                            ]
                        },
                        "full_name": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            },
                            "example": [
                                "nama tidak valid"
                            ]
                        },
                        "password": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            },
                            "example": [
                                "minimal 6 karakter"
                            ]
                        }
                    }
                },
                "message": {
                    "type": "string",
                    "example": "validasi gagal"
                }
            }
        },
        "responseswagger.VerifyEmailSuccessResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "verifikasi akun berhasil"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Backend Skripsi API",
	Description:      "Dokumentasi API untuk Aplikasi FORTISFIT",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
